### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by bcarothe** [medariox/Scrapeer#15]
I get a fatal error when running this code:
``` PHP
require 'scraper.php';

$scraper = new Scrapeer\Scraper();

$tracker = array('udp://tracker.coppersurfer.tk:6969/announce',
    'udp://tracker.leechers-paradise.org:6969/announce',
    'udp://95.213.191.124:2710/announce',
    'udp://mgtracker.org:6969/announce',
    'http://p4p.arenabg.ch:1337/announce',
    'http://www.opentrackr.org/announce');

$hash = array( '4344503B7E797EBF31582327A5BAAE35B11BDA01' );

$info = $scraper->scrape( $hash, $tracker );

print_r( $info );

// Check if we have any errors.
if ( $scraper->has_errors() ) {
    // Get the errors and print them.
	echo '<pre>';
    print_r( $scraper->get_errors() );
}
```

`
Fatal error: Uncaught Error: Call to undefined function Scrapeer\socket_create() in scraper.php:345 Stack trace: #0 scraper.php(189): Scrapeer\Scraper->udp_create_connection(2, 'tracker.coppers...', 6969) #1 scraper.php(115): Scrapeer\Scraper->scrape_udp(Array, 2, 'tracker.coppers...', 6969) #2 scraper.php(86): Scrapeer\Scraper->try_scrape('udp', 'tracker.coppers...', 6969, '', 2) #3 index.php(16): Scrapeer\Scraper->scrape(Array, Array) #4 {main} thrown in scraper.php on line 345
`

This seems to happen to a lot trackers except some few.
For example, if I switch the first and last tracker using: 

``` PHP
$tracker = array('http://www.opentrackr.org/announce', // here
    'udp://tracker.leechers-paradise.org:6969/announce',
    'udp://95.213.191.124:2710/announce',
    'udp://mgtracker.org:6969/announce',
    'http://p4p.arenabg.ch:1337/announce',
    'udp://tracker.coppersurfer.tk:6969/announce'); // and here
```

I get:

`
Array ( [0e1b1a2f5be209e1157c148faaf8afd3a3aa3824] => Array ( [seeders] => 5 [completed] => 49 [leechers] => 0 ) )
`

**Comment by bcarothe** [comment]
NOOB!

Just enabled the socket extension!
